# Generated by Django 4.1.1 on 2022-09-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_city_alter_area_options_alter_faculty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
