# Generated by Django 4.1.1 on 2022-09-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_request_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ayarlar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
    ]
