# Generated by Django 4.1.1 on 2022-09-29 00:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logotip'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Destek E-Postası'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Destek Numarası'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Başlığı'),
        ),
    ]
