# Generated by Django 4.1.1 on 2022-09-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_sitesettings_logo_sitesettings_support_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
