# Generated by Django 4.1.1 on 2022-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_slide_delete_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='language',
            field=models.CharField(default='Makedonca', max_length=255, verbose_name='Dil'),
        ),
    ]
