# Generated by Django 4.1.1 on 2022-09-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_alter_area_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='continuance',
        ),
    ]
