# Generated by Django 4.1.1 on 2022-09-29 21:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_remove_area_continuance'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='lol', editable=False, populate_from='title', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
